apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: brucexwayne/libman 
          ports:
            - containerPort: 8080  
          env:
            - name: DB_HOST
              value: "mydb-service.default.svc.cluster.local"  
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "myuser"  
            - name: DB_PASSWORD
              value: "mypassword" 
            - name: DB_NAME
              value: "mydb" 
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080  
  type: NodePort  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: postgres
          image: postgres:alpine 
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "myuser" 
            - name: POSTGRES_PASSWORD
              value: "mypassword" 
            - name: POSTGRES_DB
              value: "mydb" 
---
apiVersion: v1
kind: Service
metadata:
  name: mydb-service
spec:
  selector:
    app: mydb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP 
